version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.5.6
    container_name: "zookeeper-iss"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: kafka-iss
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper 
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-iss:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka-iss
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-iss:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
  pinot-controller:
    image: apachepinot/pinot:0.9.2
    command: "StartController -zkAddress zookeeper-iss:2181 -dataDir /data"
    container_name: "pinot-controller-iss"
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
  pinot-broker:
    image: apachepinot/pinot:0.9.2
    command: "StartBroker -zkAddress zookeeper-iss:2181"
    restart: unless-stopped
    container_name: "pinot-broker-iss"
    volumes:
      - ./config:/config
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
  pinot-server:
    image: apachepinot/pinot:0.9.2
    command: "StartServer -zkAddress zookeeper-iss:2181"
    restart: unless-stopped
    container_name: "pinot-server-iss"
    volumes:
      - ./config:/config
    depends_on:
      - pinot-broker
